# preload = $HOME/.config/images/wallhaven-12.png
# wallpaper = $HOME/.config/images/wallhaven-12.png
wallpaper {
    monitor = DP-2
    path = $HOME/.config/images/wallhaven-12.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = $HOME/.config/images/wallhaven-right.png
    fit_mode = cover
}
