#! /bin/bash
# Doing the keybinds first to make sure we are not screwed
# if something goes wrong with the rest of the loaders
killall sxhkd
sxhkd &
killall picom
picom -b
killall polybar
polybar -r secondary &
polybar -r primary &
killall dunst
dunst&
wmname LG3D

~/scripts/bspwm_subscribe.sh
~/scripts/polybar/spotify/launchlistener.sh &

feh --bg-scale ~/.config/images/wallpaper.png

xrandr --output DP-2 --primary --left-of DP-0
xrandr --output DP-0 --rotate left
bspc monitor DP-2 -d 1 2 3 4 5 6 7
bspc monitor DP-0 -d 8 9 0

bspc config focus_follows_pointer true

bspc config external_rules_command ~/.config/bspwm/bspwm-rules

ps -aux | grep slack | grep -v grep > /dev/null
if [ $? -eq 1 ]
then
    slack&
fi

ps -aux | grep Discord | grep -v grep > /dev/null
if [ $? -eq 1 ]
then
    discord&
fi

# ps -aux | grep Spotify | grep -v grep > /dev/null
# if [ $? -eq 1 ]
# then
#     spotify&
# fi

# Remap caps lock to escape
setxkbmap -option caps:escape

# Look and fell
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 5
bspc config window_gap 10
bspc config active_border_color \#B0B0B0
bspc config normal_border_color \#202020
