#! /bin/bash
# Doing the keybinds first to make sure we are not screwed
# if something goes wrong with the rest of the loaders

. $XDG_CONFIG_HOME/bspwm/launch.sh

# wmname LG3D

feh --bg-scale ~/.config/images/wallpaper.png

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config external_rules_command $XDG_CONFIG_HOME/bspwm/bspwm-rules

# If external monitor is present set workspaces 1-7 on primary and
# 8, 9 and 0 on non-primary
# Else, all workspaces on primary
EXT=DP-3-1
INT=eDP-1
if [ $(xrandr -q | grep " connected" | wc -l) == 2 ]; then
    # Take the first connected monitor that is not primary... here we could take a different
    # alternative strategy if we have multiple monitors BUT i usually use only 2 monitors 
    bspc monitor $EXT -d 1 2 3 4 5 6 7
    bspc monitor $INT -d 8 9 0

else
    bspc monitor $INT -d 1 2 3 4 5 6 7 8 9 0
fi

. $XDG_CONFIG_HOME/bspwm/polybar/launch.sh

# Remap caps lock to escape
setxkbmap -option caps:escape

# Look and fell
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 5
bspc config window_gap 5
bspc config active_border_color \#ABB2BF
bspc config normal_border_color \#282c34
