#!/usr/bin/env bash

# shellcheck disable=2046
caller="$(ps -o comm= -p $(ps -o ppid= -p $$))"
prompt="${1:-[$caller]}"
promptfg=black promptbg=red hidden=black

IFACE=$(ip -o link | grep cscotun | awk '{print $2}')

if [ "$IFACE" = "cscotun0:" ]; then
    /opt/cisco/anyconnect/bin/vpn disconnect
else
    printf "$USER\n$(rofi_askpass)\ny" | /opt/cisco/anyconnect/bin/vpn -s connect mtlvpn1.drwholdings.com/linux
fi
