[module/memory]
type = internal/memory

; Seconds to sleep between updates
; Default: 1
interval = 1

; Default: 90
; New in version 3.6.0
warn-percentage = 95
format = <label> <bar-used>

label = 󰍛

bar-used-indicator =
bar-used-width = 10
bar-used-foreground-0 = ${colors.teal}
bar-used-foreground-1 = ${colors.green}
bar-used-foreground-2 = ${colors.yellow}
bar-used-foreground-3 = ${colors.red}
bar-used-fill = ▐
bar-used-empty = ▐
bar-used-empty-foreground = #444444

ramp-used-0 = ▁
ramp-used-1 = ▂
ramp-used-2 = ▃
ramp-used-3 = ▄
ramp-used-4 = ▅
ramp-used-5 = ▆
ramp-used-6 = ▇
ramp-used-7 = █
