#            ▀                                                       ▄▀▀
#   ▄▄▄▄   ▄▄▄     ▄▄▄    ▄▄▄   ▄▄▄▄▄          ▄▄▄    ▄▄▄   ▄ ▄▄   ▄▄█▄▄
#   █▀ ▀█    █    █▀  ▀  █▀ ▀█  █ █ █         █▀  ▀  █▀ ▀█  █▀  █    █
#   █   █    █    █      █   █  █ █ █         █      █   █  █   █    █
#   ██▄█▀  ▄▄█▄▄  ▀█▄▄▀  ▀█▄█▀  █ █ █    █    ▀█▄▄▀  ▀█▄█▀  █   █    █
#   █
#   ▀
## SHAMLESSLY STOLEN FROM: DarkReaper231
##
##
## Corners
corner-radius = 15.0;

## Shadow
shadow = true;
shadow-radius = 20;
shadow-offset-x = -17;
shadow-offset-y = -7;
shadow-opacity = 0.5;
# shadow-exclude = [ "class_g = 'Polybar'"];

## other
detect-rounded-corners = true;

## fading
fading = true;
fade-delta = 0.25;
fade-in-step = 0.02;
fade-out-step = 0.02;
fade-exclude = [
];

# Default opacity of active windows.
active-opacity = 1.0;

# Default opacity of inactive windows.
inactive-opacity = 0.85;

# Opacity of window titlebars and borders.
frame-opacity = 1.0;

# Application-specific settings; these override the default `active-opacity`
opacity-rule = [
    "100:class_g = 'i3lock'"
    # "95:class_g = 'Alacritty' && focused",
    # "80:class_g = 'Alacritty' && !focused"
];
