#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
export EDITOR='emacs'
export GIT_EDITOR=emacs
export TERMINAL=st

export PATH=~/.emacs.d/bin:$PATH
export PATH=~/bin:$PATH
export PATH=~/bin/bin:$PATH
export PATH=~/.cargo/bin:$PATH
