#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias vim='nvim'
alias vi='nvim'
export EDITOR='emacs'
export GIT_EDITOR=emacs

alias adog="git log --all --decorate --oneline --graph"
alias gst="git status"
alias ll="ls -al"
alias tmux="tmux -2"

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

if [[ -r ~/.zshrc_local ]]; then
    source ~/.zshrc_local
fi
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PIPENV_PYTHON="$PYENV_ROOT/shims/python"
export PIPENV_PYTHON="~.pyenv/versions/"
